name: Deploy to EC2 Via CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2 Via CI/CD
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
          echo "Starting deployment process..."

          # Ensure NVM and Node.js are installed
          echo "Installing Node.js via NVM..."
          if ! command -v nvm &> /dev/null; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          fi
          nvm install node

          # Ensure PM2 is installed
          echo "Installing PM2..."
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          # Set repository details
          REPO_URL="https://github.com/mizanur090148/github-actions-ec2.git"
          BRANCH="main"
          REPO_DIR="$HOME/github-aws-ec2"

          # Clone or update the repository
          if [ -d "$REPO_DIR/.git" ]; then
            echo "Pulling latest changes..."
            cd "$REPO_DIR"
            git reset --hard HEAD # Ensure a clean working directory
            git pull origin "$BRANCH"
          else
            echo "Cloning repository..."
            git clone "$REPO_URL" "$REPO_DIR"
            cd "$REPO_DIR"
          fi

          # Navigate to the correct subdirectory
          cd "$REPO_DIR/simple-web-server"

          # Install dependencies
          echo "Installing dependencies..."
          npm install

          # Restart or start the application with PM2
          echo "Starting/restarting application with PM2..."
          pm2 start server.js --name "simple-web-server" || pm2 restart "simple-web-server"

          echo "Deployment complete!"
          '
